---
- name: Check web app for Normal State
  uri:
    url: "http://{{ ansible_host }}"
    return_content: yes
  register: webpage

- name: Fail if Normal is not in the page content
  fail:
  when: "'Normal' not in webpage.content"
